apiVersion: v1
kind: Service
metadata:
  name: postgresql-external
  labels:
    version: 1.0.0
spec:
  selector:
    sfs: postgresql-sfs
  ports:
    - name: postgresql-external
      port: 5432
      targetPort: 5432
      nodePort: 30030
  type: NodePort